StudentWork/emcain-student/seabeck_draft/seabeck_draft/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from my_app import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index, name='index'),
    url(r'^login_needed/', views.login_needed, name='login_needed'),
    url(r'^logout_view/', views.logout_view, name='logout_view'),
    url(r'^logout_successful/', views.logout_successful, name='logout_successful'),


#    url(r'^new_family.html', views.new_family, name='new_family'),
    url(r'^edit_family/(?P<family_id>[0-9]+)/$', views.edit_family,
        name='edit_family'),
    url(r'^edit_camper/(?P<camper_id>[0-9]+)/$', views.edit_camper, name='edit_camper'),

    # url(r'^api_campers/(?P<family_id>[0-9]+)/$', views.api_campers, name='api_campers'),

    # url(r'^dynamic_detail/(?P<family_id>[0-9]+)/$', views.dynamic_detail, name='dynamic_detail'),

    url(r'^api_campers/$', views.api_campers, name='api_campers'),

    url(r'^detail/$', views.detail, name='detail'),

    url(r'^login/$', views.login_view, name='login_view'),
    url(r'^register/$', views.register_view, name='register_view')
#    url(r'(?P<family_id>[0-9]+)/$', views.edit, name='edit'),

    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

StudentWork/emcain-student/seabeck_draft/my_app/models.py
from django.contrib.auth.models import User
from django.db import models
from datetime import *
# Classes:
# Family


# USER TYPES

class Family(models.Model):
    # first_name = models.CharField(max_length=50)
    # last_name = models.CharField(max_length=50)
    # email = models.EmailField()
    user = models.OneToOneField(User)
    phone = models.CharField(max_length=15, default="needed")  # will create validation later
    total_owed = models.DecimalField(max_digits=20, decimal_places=4, default=0)
    total_paid = models.DecimalField(max_digits=20, decimal_places=4, default=0)

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name

    def __unicode__(self):
        return self.user.first_name + " " + self.user.last_name


class Staff(models.Model):

    user = models.ForeignKey(User)
    is_admin = models.BooleanField(default=False)
    is_webmaster = models.BooleanField(default=False)


# Campers
class Camper(models.Model):
    family = models.ForeignKey(Family)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    under_18 = models.BooleanField()
    dob = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.first_name + " " + self.last_name

    def __unicode__(self):
        return unicode(self.first_name + " " + self.last_name)


class EventYear(models.Model):
    start_date = models.DateField()
    end_date = models.DateField()

    def get_year(self):
        return int(self.start_date.year)

    def __str__(self):
        return "Camp Year " + str(self.start_date.year)

    def __unicode__(self):
        return unicode("Camp Year ") + unicode(self.start_date.year)


class Attendance(models.Model):  # i.e. Campers by year
    event_year = models.ForeignKey(EventYear)
    camper = models.ForeignKey(Camper)
    grade = models.IntegerField(null=True, blank=True)

    def age_at_start(self):
        try:
            return int(self.event_year.get_year()) - int(self.camper.dob.year)
            #need to fix this to use specific date
        except:
            return "unknown age"

    def __str__(self):
        return self.camper.first_name + " " + self.camper.last_name + " - " + str(self.event_year)

    def __unicode__(self):
        return self.camper.first_name + " " + self.camper.last_name + " - " + unicode(self.event_year)



class Shirt(models.Model):
    size_name = models.CharField(max_length=10)

    def __str__(self):
        return self.size_name

    def __unicode__(self):
        return self.size_name

    # instead make 6 instances of shirt with size assigned


class ShirtOrder(models.Model):
    attendance = models.ForeignKey(Attendance)  # recursion
    shirt = models.ForeignKey(Shirt)  # recursion

    def __str__(self):
        return "Camper: " + str(self.attendance) \
               + " shirt order: " + self.shirt.size_name

    def __unicode__(self):
        return "Camper: " + unicode(self.attendance) \
               + " shirt order: " + self.shirt.size_name


# class MeatPreference(models.Model):
#     preference_name = models.TextField(max_length=20)
#
#     def __str__(self):
#         return self.preference_name
#
#     def __unicode__(self):
#         return self.preference_name


# class AllergyType(models.Model):
#     type_name = models.TextField(max_length=20)
#
#     def __str__(self):
#         return self.type_name
#
#     def __unicode__(self):
#         return self.type_name


class FoodPreference(models.Model):
    camper = models.ForeignKey(Camper)
    # meat_pref = models.ForeignKey(MeatPreference)
    # gluten_free = models.BooleanField()
    # dairy_free = models.BooleanField()
    # other = models.TextField()
    # severity = models.ForeignKey(AllergyType)  # change eventually to new table.

    vegan = models.BooleanField(default=False)
    vegetarian = models.BooleanField(default=False)
    gluten_free = models.BooleanField(default=False)
    dairy_free = models.BooleanField(default=False)

    def __str__(self):
        output = ""
        if self.vegan:
            output += "vegan, "
        if self.vegetarian:
            output += "vegetarian, "
        if self.gluten_free:
            output += "gluten free, "
        if self.dairy_free:
            output += "dairy free, "
        return output[:-2]

    def __unicode__(self):

        output = ""
        if self.vegan:
            output += "vegan, "
        if self.vegetarian:
            output += "vegetarian, "
        if self.gluten_free:
            output += "gluten free, "
        if self.dairy_free:
            output += "dairy free, "
        return unicode(output[:-2])



# Rates
class Rate(models.Model):
    # find out how to restrict this to preset types e.g. housing, registration, tshirt
    type = models.CharField(max_length=20)
    # e.g. SM (if tshirt), Pines (if housing)
    item = models.IntegerField()
    cost_per = models.DecimalField(max_digits=20, decimal_places=4)  # do as dollars or as cents???

    def __str__(self):
        return "type: " + self.type \
               + "item: " + self.item \
               + "rate: $" + str(self.cost_per)

    def __unicode__(self):
        return "type: " + self.type \
               + "item: " + self.item \
               + "rate: $" + str(self.cost_per)

StudentWork/emcain-student/seabeck_draft/my_app/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader

from django.core.urlresolvers import reverse

from django.shortcuts import get_object_or_404, render, redirect

from .models import Family, Camper, Rate, EventYear, Attendance

import json

# def index(request):
#     return HttpResponse("Hello, world. You're at the polls index.")

# def login_needed(request):
#     template = loader.get_template('seabeck_draft/login_needed.html')
#     return render(template, 'seabeck_draft/login_needed.html', {})
#


def login_view(request):
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect("/")

    return render(request, 'seabeck_draft/login.html', {})


def register_view(request):

    if request.POST:
        user = User()
        user.username = request.POST['username']
        user.email = request.POST['username']
        user.set_password(request.POST['password'])
        user.first_name = request.POST['first_name']
        user.last_name = request.POST['last_name']
        user.save()

        family = Family()
        family.user = user
        family.phone = request.POST['phone']
        family.save()

        camper = Camper()
        camper.family = family
        camper.first_name = user.first_name
        camper.last_name = user.last_name
        camper.under_18 = False
        camper.dob = None
        camper.save()

        return HttpResponseRedirect("/login/")

    return render(request, 'seabeck_draft/register.html', {})


def logout_view(request):
    logout(request)
    return redirect("/logout_successful/")


@login_required(login_url='/login_needed/')
def index(request):
    families_list = Family.objects.order_by("user__last_name")
#often use two underscores to represent dot/fk relationship
    template = loader.get_template('seabeck_draft/index.html')
    context = RequestContext(request, {'families_list': families_list})

    return HttpResponse(template.render(context))

@login_required()
def detail(request):

    family = get_object_or_404(Family, user=request.user)
    return render(request, 'seabeck_draft/detail.html', {'family': family})

@login_required()
def dynamic_detail(request, family_id):
    # family = get_object_or_404(Family, pk=family_id)
    return render(request, 'seabeck_draft/dynamic_detail.html', {})


def api_campers(request):

    years = EventYear.objects.all()
    current_year = list(reversed(years))[0]
    campers = Camper.objects.filter(family__user=request.user)
    output = []
    print(current_year)
    for camper in campers:
        in_current_year = len(Attendance.objects.filter(camper=camper, event_year=current_year)) > 0


        output.append({"id":camper.id, "name": camper.first_name + " " + camper.last_name,  "in_current_year" : in_current_year})


    return HttpResponse(json.dumps(output, indent=4), content_type="application/json")


# def api_detail(request, family_id):
#         family = get_object_or_404(Family, pk=family_id)
#     return render(request, 'seabeck_draft/detail.html', {'family': family})
#


def login_needed(request):
    return render(request, 'seabeck_draft/login_needed.html')

def logout_successful(request):
    return render(request, 'seabeck_draft/logout_successful.html')

def edit_family(request, family_id):

    if family_id == 0:
        print "new"
        family = Family()
    else:
        print "existing"
        family = get_object_or_404(Family, pk=family_id)

    filtered_family_list = Family.objects.filter(id=family_id)

#    if len(filtered_family_list) > 0:
    family = filtered_family_list[0]
#    else:
#        family = Family()

    if request.POST:
        print(request.POST)
        family.first_name = request.POST["first_name"]
        family.last_name = request.POST["last_name"]
        family.email = request.POST["email"]
        family.phone = request.POST["phone"]
        family.save()
        return HttpResponseRedirect("/")

    return render(request, 'seabeck_draft/edit_family.html', {'family': family})


def new_family(request):

    family = Family()

    if request.POST:
        print(request.POST)
        family.first_name = request.POST["first_name"]
        family.user.last_name = request.POST["user.last_name"]
        family.email = request.POST["email"]
        family.phone = request.POST["phone"]
        family.save()
        return HttpResponseRedirect("/")

    return render(request, 'seabeck_draft/new_family.html', {'family': family})


def edit_camper(request, camper_id):

    if camper_id == "0":
        camper = Camper()
    else:
        camper = get_object_or_404(Camper, pk=camper_id)

    filtered_camper_list = Camper.objects.filter(id=camper_id)

    if len(filtered_camper_list) > 0:
        camper = filtered_camper_list[0]
    else:
        camper = Camper()

    if request.POST:
        print(request.POST)
        camper.first_name = request.POST["first_name"]
        camper.last_name = request.POST["last_name"]
        camper.under_18 = request.POST["under_18"]
        camper.save()
        return HttpResponseRedirect("/")

    return render(request, 'seabeck_draft/edit_camper.html', {'camper': camper})

StudentWork/emcain-student/seabeck_draft/my_app/templates/seabeck_draft/detail.html
{% extends "seabeck_draft/logged_in_base_template.html" %}




{% block content %}
    {% load staticfiles %}

    <link rel='stylesheet' type="text/css" href='{% static "my_app/css/bootstrap-theme.css" %}'/>
    <link rel='stylesheet' type="text/css" href='{% static "my_app/css/custom.css" %}'/>
    <style>
        #campers_of_family {
            color: slategray;
            font-style: italic;
        }

        div .active {
            color: green;
            font-weight: bold;
            font-style: normal;
        }



    </style>


    <h1>Hello, {{ family.user.first_name }} {{ family.user.last_name }}!</h1>
    <h2>These are the campers you have signed up in the past.</h2>

{#    This section will be filled in by the draw_detail script. #}
    <div id="campers-list">
        Loading campers...
    </div>

    <br><br>
    <a href="/">Return to main page</a>

    <script src='{% static "my_app/js/draw_detail.js" %}'></script>

{% endblock %}

StudentWork/emcain-student/seabeck_draft/my_app/templates/seabeck_draft/dynamic_detail.html
{% load staticfiles %}
<script src="{% static "my_app/js/dynamic-detail-script.js" %}"></script>

<h2>These are the campers {{ family.user.first_name }} {{ family.user.last_name }} has signed up in the
    past:</h2>
<p> this is the dynamic page. </p>
<ul>
    {% if family.camper_set.all < 0 %}
        <p>You have not registered anyone.</p>

    {% else %}


        <li id="camper_{{ camper.id }}" class="camper_li">{{ camper.first_name }} {{ camper.last_name }} --

            <span class="child_adult"></span>
            --
            {% if forloop.last %}
                {{ a.age_at_start }}
            {% endif %}
            --

            {{ a.age_at_start }}

            <button id="edit_camper_{{ camper.id }}" class="edit_camper_button">Edit</button>
            <button id="remove_camper_{{ camper.id }}" class="remove_camper_button">Remove</button>


            <form method="post">
                {% csrf_token %}


                First name: <input value="{{ camper.first_name }}" name="first_name" type="text">
                Last name: <input value="{{ camper.last_name }}" name="last_name" type="text">
                <br>
                Age: <select value="{{ camper.under_18 }}" name="under_18">
                <option value="Null"></option>
                <option value="False">Adult (18+)</option>
                <option value="True">Child (under 18)</option>
            </select>
                Birth date: <input value="{{ camper.dob }}" name="dob" type="date">
                <br>
                <input type="submit" value="SAVE"/>
            </form>


        </li>


    {% endif %}
</ul>

<br><br>
<button>Add Camper</button>

<a href="/">Return to main page</a>

StudentWork/emcain-student/seabeck_draft/my_app/templates/seabeck_draft/edit_camper.html
{% load staticfiles %}
{% block title %}
<h1>Edit Camper</h1>
{% endblock %}

{% block others %}



<ul>
    {% for indiv in camper.family.camper_set.all %}
        {% if indiv != camper %}
            <li>{{ indiv.first_name }} {{ indiv.last_name }} --
                {% if indiv.under_18 == True %}
                    Child
                {%  else%}
                    Adult
                {% endif %}
                --
                {% for a in indiv.attendance_set.all %}
                    {% if forloop.last %}
                        {{ a.age_at_start }}
                    {% endif %}
                {% endfor %}
                --
                {% for a in indiv.food_preference_set.all %}

                        {{ a.age_at_start }}
                {% endfor %}

            <a href="/edit_camper/{{ indiv.id }}">edit</a>

        </li>
        {% endif %}
    {% endfor %}
</ul>

{% endblock %}

{% block content %}

<form method="post">
    {% csrf_token %}
{#    <h1>#}
{#        {% if camper.id %}#}
{#        Edit Camper:#}
{#        {% else %}#}
{#        New Camper:#}
{#        {% endif %}#}
{#    </h1>#}

    First name: <input value="{{ camper.first_name  }}" name="first_name" type="text">
    Last name: <input value="{{ camper.last_name  }}" name="last_name" type="text">
    <br>
    Age: <select value="{{ camper.under_18 }}" name="under_18">
        <option value="Null"></option>
        <option value="False">Adult (18+)</option>
        <option value="True">Child (under 18)</option>
    </select>
    Birth date: <input value="{{ camper.dob  }}" name="dob" type="date">
    <br>
    <input type="submit" value="SAVE"/>
</form>

{% endblock %}

{% block last %}
    <a href="/">Return to Families List</a>
{% endblock %}

StudentWork/emcain-student/seabeck_draft/my_app/templates/seabeck_draft/edit_family.html
{% load staticfiles %}
{% block title %}
Edit Family
{% endblock %}
{% block content %}

<form method="post">
    {% csrf_token %}
    <h1>
        {% if family.id %}
        Edit Family:
        {% else %}
        New Family:
        {% endif %}
    </h1>

    First name: <input value="{{ family.first_name  }}" name="first_name" type="text">
    Last name: <input value="{{ family.last_name  }}" name="last_name" type="text">
    <br>
    Phone number: <input value="{{ family.phone  }}" name="phone" type="text">
    Email address: <input value="{{ family.email  }}" name="email" type="text">
    <br>
    <input type="submit" value="SAVE"/>
</form>



{% endblock %}

StudentWork/emcain-student/seabeck_draft/my_app/templates/seabeck_draft/index.html
<h1>Welcome, {{ family.user.first_name }} {{ family.user.last_name }}!</h1>

{%  if families_list %}
    <ul>
    {%  for family in families_list %}
        <li><a href="/detail/{{ family.id }}">{{ family }}</a>
            phone: {{ family.phone }}
            email: {{ family.user.email }}
        <a href="/edit_family/{{ family.id }}">edit</a>

        </li>

    {%  endfor %}
    </ul>
{% else %}
    <p>No one has registered. </p>
{% endif %}

<a href="new_family.html">New Registration</a>

StudentWork/emcain-student/seabeck_draft/my_app/templates/seabeck_draft/logged_in_base_template.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Camp Registration App
        {% endblock %}
    </title>
    <link rel='stylesheet' type="text/css" href='{% static "my_app/css/bootstrap-theme.css" %}'/>
    <link rel='stylesheet' type="text/css" href='{% static "my_app/css/bootstrap.css" %}'/>
    <link rel='stylesheet' type="text/css" href='{% static "my_app/css/custom.css" %}'/>

</head>
<body>
<header>
    {% block header %}
        <ol class="breadcrumb">
            <li><a href="#">family profile</a>
            </li>
            <li class="active">this year's campers</li>
        </ol>
    {% endblock %}
</header>

<div class="outer-div">
    {% block content %}
        content goes here
    {% endblock %}
</div>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src='{% static "my_app/js/bootstrap.js" %}'></script>
<script>
        console.log ('stuff');
        console.log( '{{ family.id }}' );
        fetch("/api_campers/");
</script>
</body>
</html>

StudentWork/emcain-student/seabeck_draft/my_app/templates/seabeck_draft/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<h1>
    Login
</h1>
<form method="post">
    {% csrf_token %}
    <label>
        <p>Email/Username</p>
        <input name="username" type="email">
    </label>
    <label>
        <p>Password</p>
        <input name="password" type="password">
    </label>
        <input type="submit" value="submit">
</form>
</body>
</html>

StudentWork/emcain-student/seabeck_draft/my_app/templates/seabeck_draft/login_needed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login Required</title>
</head>
<body>

<h1>Login Required</h1>

{#https://docs.djangoproject.com/en/1.8/howto/static-files/#}
{% load staticfiles %}
<img src='{% static "my_app/image/no-sign.jpg" %}' alt="nope" height="100px" width="100px"/>

<p>Sorry, you must be logged into your account to do that.</p>
<p><a href="/login/">Log into an existing account</a> or <a href="/register">create a new account.</a></p>
<p>See the <a href="/faq-placeholder">FAQ</a> if you are having trouble. </p>

</body>
</html>

StudentWork/emcain-student/seabeck_draft/my_app/templates/seabeck_draft/logout_successful.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout Successful</title>
</head>
<body>

<h1>Logout Successful</h1>

{#https://docs.djangoproject.com/en/1.8/howto/static-files/#}
{% load staticfiles %}
<img src='{% static "my_app/image/check.jpg" %}' alt="yay!" height="100px" width="100px"/>

<p>You have successfully logged out.</p>
<p><a href="/login/">Log into an existing account</a> or <a href="/register">create a new account.</a></p>
<p>See the <a href="/faq-placeholder">FAQ</a> if you are having trouble. </p>

</body>
</html>

StudentWork/emcain-student/seabeck_draft/my_app/templates/seabeck_draft/logout_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
Logging out, please wait...
</body>
</html>

StudentWork/emcain-student/seabeck_draft/my_app/templates/seabeck_draft/new_camper.html
{% load staticfiles %}
{% block title %}
New Camper
{% endblock %}

{% block others %}
<h1>Campers registered by {{ camper.family.first_name }} {{ camper.family.last_name }}</h1>

<ul>
    {% for indiv in camper.family.camper_set.all %}
        {% if indiv != camper %}
            <li>{{ indiv.first_name }} {{ indiv.last_name }} --
                {% if indiv.under_18 == True %}
                    Child
                {%  else%}
                    Adult
                {% endif %}
                --
                {% for a in indiv.attendance_set.all %}
                    {% if forloop.last %}
                        {{ a.age_at_start }}
                    {% endif %}
                {% endfor %}
                --
                {% for a in indiv.food_preference_set.all %}

                        {{ a.age_at_start }}
                {% endfor %}

            <a href="/edit_camper/{{ indiv.id }}">edit</a>

        </li>
        {% endif %}
    {% endfor %}
</ul>

{% endblock %}

{% block content %}

<form method="post">
    {% csrf_token %}

    First name: <input value="{{ camper.first_name  }}" name="first_name" type="text">
    Last name: <input value="{{ camper.last_name  }}" name="last_name" type="text">
    <br>
    Age: <select value="{{ camper.under_18 }}" name="under_18">
        <option value="Null"></option>
        <option value="False">Adult (18+)</option>
        <option value="True">Child (under 18)</option>
    </select>
    Birth date: <input value="{{ camper.dob  }}" name="dob" type="date">
    <br>
    <input type="submit" value="SAVE"/>
</form>

{% endblock %}

{% block last %}
    <a href="/">Return to Families List</a>
{% endblock %}

StudentWork/emcain-student/seabeck_draft/my_app/templates/seabeck_draft/new_family.html
{% load staticfiles %}
{% block title %}
Edit Family
{% endblock %}
{% block content %}

<form method="post">
    {% csrf_token %}
    <h1>
        New Registration:
    </h1>

    First name: <input value="{{ family.first_name  }}" name="first_name" type="text">
    Last name: <input value="{{ family.last_name  }}" name="last_name" type="text">
    <br>
    Phone number: <input value="{{ family.phone  }}" name="phone" type="text">
    Email address: <input value="{{ family.email  }}" name="email" type="text">
    <br>
    <input type="submit" value="SAVE"/>
</form>



{% endblock %}

StudentWork/emcain-student/seabeck_draft/my_app/templates/seabeck_draft/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<h1>
    Register
</h1>
<form method="post">
    {% csrf_token %}
    <label>
        <p>Email</p>
        <input name="username" type="email">
    </label>

    <label>
        <p>Password</p>
        <input name="password" type="password">
    </label>

    <label>
        <p>First Name</p>
        <input name="first_name" type="text">
    </label>

    <label>
        <p>Last Name</p>
        <input name="last_name" type="text">
    </label>

    <label>
        <p>Phone Number</p>
        <input name="phone" type="text">
    </label>

    <input type="submit" value="Register">


</form>
</body>
</html>